// ========== CATALOGUE DES OEUVRES — THÈME 2026 : LES ANIMAUX ET NOUS ==========
// Données complètes pour le catalogue filtrable sur la page d'accueil
// Chaque oeuvre : id, titre, auteur, année, catégorie, difficulté, résumé, conseil exam, citation

const OEUVRES = [

    // ==================== LITTÉRATURE (37 oeuvres) ====================

    {
        id: 'roman-de-renart',
        title: 'Le Roman de Renart',
        author: 'Anonyme',
        year: 'XIIe-XIIIe siècle',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🦊',
        coverGradient: 'linear-gradient(135deg, #6c5ce7, #a29bfe)',
        summary: "Recueil de récits médiévaux où Renart le goupil (renard) trompe et ridiculise les autres animaux, notamment Ysengrin le loup. C'est une satire de la société féodale : chaque animal représente un type social (le roi, le paysan, le prêtre). L'oeuvre montre que l'anthropomorphisme animal est une tradition très ancienne en littérature française.",
        examTip: "Utilise cette oeuvre pour illustrer la tradition médiévale de l'anthropomorphisme et la satire sociale par les animaux. Parfait en introduction historique.",
        keyQuote: ''
    },
    {
        id: 'grande-ourse',
        title: 'La Grande Ourse',
        author: 'Maylis Adhémar',
        year: '2023',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '🐻',
        coverGradient: 'linear-gradient(135deg, #7c6ce7, #b29bfe)',
        summary: "Roman contemporain qui explore la cohabitation entre humains et ours dans les Pyrénées. L'autrice met en scène les tensions entre éleveurs, écologistes et la faune sauvage. Le récit interroge la place de l'animal sauvage dans nos territoires et la difficulté du « vivre ensemble » entre espèces.",
        examTip: "Utilise cette oeuvre pour parler du conflit contemporain entre activités humaines et réintroduction d'espèces sauvages. Argument concret et actuel.",
        keyQuote: ''
    },
    {
        id: 'clerambard',
        title: 'Clérambard',
        author: 'Marcel Aymé',
        year: '1950',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '🐖',
        coverGradient: 'linear-gradient(135deg, #5c4ce7, #9b8bfe)',
        summary: "Pièce de théâtre où le comte de Clérambard, brutal et tyrannique, reçoit une vision de saint François d'Assise et se convertit radicalement : il libère ses animaux, accueille les marginaux et rejette la violence. L'oeuvre explore le basculement d'un rapport de domination vers la compassion envers toutes les créatures vivantes.",
        examTip: "Utilise cette pièce pour illustrer la conversion morale : passer de la domination à la compassion envers les animaux, inspirée par saint François d'Assise.",
        keyQuote: ''
    },
    {
        id: 'baudelaire-chats',
        title: '"Le chat" / "Les chats" (Les Fleurs du Mal)',
        author: 'Charles Baudelaire',
        year: '1857',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '🐈‍⬛',
        coverGradient: 'linear-gradient(135deg, #6b5ad7, #a89bef)',
        summary: "Poèmes emblématiques où le chat incarne le mystère, la sensualité et la beauté. Baudelaire voit dans le chat un double poétique : indépendant, insaisissable, à la fois doux et cruel. Le chat devient un miroir de l'âme du poète, un être à la frontière entre le familier et l'étrange.",
        examTip: "Utilise Baudelaire pour montrer comment l'animal devient une figure poétique et symbolique, reflet de l'intériorité humaine. Le chat = mystère + beauté + altérité.",
        keyQuote: "« Viens, mon beau chat, sur mon coeur amoureux ; / Retiens les griffes de ta patte. »"
    },
    {
        id: 'colloque-chiens',
        title: 'Le Colloque des chiens',
        author: 'Miguel de Cervantes',
        year: '1613',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '🐕',
        coverGradient: 'linear-gradient(135deg, #7d6df8, #b3a5ff)',
        summary: "Nouvelle picaresque où deux chiens, Cipión et Berganza, obtiennent miraculeusement la parole et en profitent pour raconter leur vie et critiquer la société espagnole. Le regard animal permet une satire décalée : les chiens observent les défauts humains avec lucidité. Un texte fondateur du « point de vue animal » en littérature.",
        examTip: "Utilise cette oeuvre pour montrer que donner la parole aux animaux permet de critiquer la société humaine avec un regard neuf et distancié.",
        keyQuote: ''
    },
    {
        id: 'arche-titanic',
        title: "L'Arche Titanic",
        author: 'Éric Chevillard',
        year: '2024',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'difficile',
        diffLabel: 'Difficile',
        icon: '🚢',
        coverGradient: 'linear-gradient(135deg, #5b4bd7, #9a8aef)',
        summary: "Texte expérimental qui dresse un inventaire poétique et ironique des espèces animales menacées ou disparues. Le titre mêle l'Arche de Noé (sauvetage) et le Titanic (naufrage) : nous sommes sur un bateau qui coule avec tous les animaux à bord. Chevillard dénonce l'extinction de masse avec un humour noir et une écriture virtuose.",
        examTip: "Utilise cette oeuvre pour parler de la sixième extinction de masse et du devoir de mémoire envers les espèces disparues. Métaphore puissante : Arche + Titanic = sauvetage impossible.",
        keyQuote: ''
    },
    {
        id: 'colette-chatte-dialogues',
        title: 'La Chatte ; Dialogues de bêtes',
        author: 'Colette',
        year: '1933 / 1904',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '🐱',
        coverGradient: 'linear-gradient(135deg, #7565e7, #ab9efe)',
        summary: "Dans 'La Chatte', un homme préfère sa chatte Saha à sa femme, ce qui détruit son couple. Dans 'Dialogues de bêtes', Colette donne la parole à un chien et un chat qui commentent leur vie quotidienne. Colette excelle à décrire la sensibilité animale avec finesse et tendresse, montrant que l'animal a une vie intérieure riche.",
        examTip: "Utilise Colette pour montrer la proximité affective homme-animal et l'idée que l'animal possède une sensibilité propre. Colette = observation fine + empathie animale.",
        keyQuote: ''
    },
    {
        id: 'cyrano-etats-soleil',
        title: 'Histoire comique des États et Empires du Soleil',
        author: 'Cyrano de Bergerac',
        year: '1662',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'difficile',
        diffLabel: 'Difficile',
        icon: '☀️',
        coverGradient: 'linear-gradient(135deg, #6458d7, #a090ef)',
        summary: "Récit de voyage imaginaire sur le Soleil où le narrateur rencontre des sociétés d'oiseaux qui jugent les humains pour leurs crimes contre les animaux. Cyrano renverse la hiérarchie : ce sont les animaux qui sont civilisés et les hommes qui sont barbares. Un texte précurseur de la pensée antispéciste, écrit au XVIIe siècle.",
        examTip: "Utilise cette oeuvre pour montrer le renversement de perspective : les animaux jugent les humains. Argument clé pour l'antispécisme avant l'heure.",
        keyQuote: ''
    },
    {
        id: 'cannibale',
        title: 'Cannibale',
        author: 'Didier Daeninckx',
        year: '1998',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🏛️',
        coverGradient: 'linear-gradient(135deg, #8070f7, #bab0ff)',
        summary: "Roman court qui raconte l'histoire vraie de Kanaks exposés dans un zoo humain lors de l'Exposition coloniale de 1931 à Paris, échangés contre des crocodiles. Daeninckx dénonce la bestialisation de l'autre : traiter des humains comme des animaux de zoo. Le titre 'Cannibale' retourne l'accusation contre les colonisateurs.",
        examTip: "Utilise cette oeuvre pour parler de la frontière floue humain/animal et de la « bestialisation » comme outil d'oppression. Argument puissant sur les zoos humains.",
        keyQuote: ''
    },
    {
        id: 'regne-animal-del-amo',
        title: 'Règne animal',
        author: 'Jean-Baptiste Del Amo',
        year: '2016',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'difficile',
        diffLabel: 'Difficile',
        icon: '🐷',
        coverGradient: 'linear-gradient(135deg, #5e4ec7, #9c8cdf)',
        summary: "Fresque familiale sur un siècle d'élevage porcin, de la petite ferme traditionnelle à l'industrie intensive. Del Amo décrit crûment la violence de l'exploitation animale et la déshumanisation des éleveurs eux-mêmes. Le roman montre que la brutalité envers les animaux détruit aussi les humains. Texte dur mais marquant.",
        examTip: "Utilise cette oeuvre pour dénoncer l'élevage industriel et montrer que la violence faite aux animaux déshumanise aussi les humains. Argument choc.",
        keyQuote: ''
    },
    {
        id: 'eluard-animaux',
        title: 'Les Animaux et leurs hommes',
        author: 'Paul Éluard',
        year: '1920',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '🕊️',
        coverGradient: 'linear-gradient(135deg, #7262e7, #a898fe)',
        summary: "Recueil poétique surréaliste où Éluard inverse le rapport de possession : ce ne sont pas « les hommes et leurs animaux » mais « les animaux et leurs hommes ». Les poèmes brefs et imagés décrivent des animaux familiers (chat, chien, poisson) avec un regard neuf et tendre. Le titre lui-même est un programme.",
        examTip: "Utilise ce recueil pour montrer l'inversion du rapport de possession : les animaux possèdent leurs humains. Le titre même est un argument sur le renversement hiérarchique.",
        keyQuote: ''
    },
    {
        id: 'esope-fables',
        title: 'Fables',
        author: 'Ésope',
        year: 'VIe siècle av. J.-C.',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🐢',
        coverGradient: 'linear-gradient(135deg, #8575f7, #bdb0ff)',
        summary: "Les toutes premières fables animalières de la littérature occidentale. Ésope, esclave grec, invente des récits courts avec des animaux parlants pour enseigner des leçons de vie. Le lièvre et la tortue, le corbeau et le renard : tous ces classiques viennent de lui. La Fontaine s'en inspirera 2000 ans plus tard.",
        examTip: "Utilise Ésope comme point de départ historique : il est l'inventeur de la fable animalière. Indispensable en introduction pour remonter aux origines du genre.",
        keyQuote: ''
    },
    {
        id: 'gary-chien-blanc',
        title: 'Chien blanc',
        author: 'Romain Gary',
        year: '1970',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '🐕‍🦺',
        coverGradient: 'linear-gradient(135deg, #6d5de8, #a49bff)',
        summary: "Gary recueille un chien dressé à attaquer les Noirs (un « chien blanc » ségrégationniste). Il tente de le rééduquer, mais le chien est retourné : il attaque désormais les Blancs. Le roman dénonce le racisme américain en montrant que la haine est un dressage, pas un instinct. L'animal est le miroir de la violence humaine.",
        examTip: "Utilise cette oeuvre pour montrer que l'animal est un révélateur du racisme humain. Le dressage du chien = métaphore de l'éducation à la haine.",
        keyQuote: ''
    },
    {
        id: 'gary-racines-ciel',
        title: 'Les Racines du ciel',
        author: 'Romain Gary',
        year: '1956',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'difficile',
        diffLabel: 'Difficile',
        icon: '🐘',
        coverGradient: 'linear-gradient(135deg, #6050d8, #9d8def)',
        summary: "Prix Goncourt 1956. Morel, un homme seul, se bat pour protéger les éléphants du Tchad contre le braconnage. Pour lui, défendre les éléphants, c'est défendre la dignité et la liberté humaines. Roman précurseur de l'écologie politique : protéger la nature n'est pas un luxe, c'est une nécessité morale.",
        examTip: "Utilise Gary pour l'engagement écologique avant l'heure. L'éléphant = symbole de liberté et de grandeur menacée. Argument fondateur de l'écologie littéraire.",
        keyQuote: "« Quand on aura coupé le dernier arbre et tué le dernier éléphant, il n'y aura plus de racines du ciel pour l'homme. »"
    },
    {
        id: 'haines-etoiles-neige',
        title: 'Les étoiles, la neige, le feu',
        author: 'John Haines',
        year: '1989',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '❄️',
        coverGradient: 'linear-gradient(135deg, #7868e8, #ae9fff)',
        summary: "Récit autobiographique d'un poète américain qui vit 25 ans en ermite dans la nature sauvage de l'Alaska. Haines décrit sa cohabitation quotidienne avec les animaux sauvages (loups, élans, oiseaux) et développe un rapport de respect et d'interdépendance avec eux. Un témoignage sur la vie en harmonie avec la faune.",
        examTip: "Utilise cette oeuvre pour illustrer la possibilité d'un rapport harmonieux et respectueux entre l'homme et l'animal sauvage. Argument pour la cohabitation.",
        keyQuote: ''
    },
    {
        id: 'hochet-animal-biographe',
        title: "L'Animal et son biographe",
        author: 'Stéphanie Hochet',
        year: '2017',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '📖',
        coverGradient: 'linear-gradient(135deg, #6a58d8, #a192ef)',
        summary: "Essai littéraire où Hochet explore comment les écrivains ont mis en scène les animaux à travers l'histoire. Elle montre que raconter la vie d'un animal, c'est toujours aussi parler de nous. Le livre est un panorama des représentations animales en littérature, de l'Antiquité à nos jours.",
        examTip: "Utilise cette oeuvre comme source méta-littéraire : elle analyse comment les écrivains parlent des animaux. Parfait pour une réflexion sur la représentation animale.",
        keyQuote: ''
    },
    {
        id: 'homere-argos',
        title: 'Odyssée, chant XVII (Argos le chien)',
        author: 'Homère',
        year: 'VIIIe siècle av. J.-C.',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🏺',
        coverGradient: 'linear-gradient(135deg, #8272f8, #bab0ff)',
        summary: "Scène mythique : Ulysse revient à Ithaque après 20 ans déguisé en mendiant. Personne ne le reconnaît, sauf son vieux chien Argos, couché sur un tas de fumier. Le chien remue la queue, couche les oreilles... puis meurt. La fidélité animale absolue, au-delà du temps et de la misère.",
        examTip: "Utilise Argos pour illustrer la fidélité animale inconditionnelle, la reconnaissance au-delà des apparences. Scène universellement connue, très efficace en dissertation.",
        keyQuote: ''
    },
    {
        id: 'hugo-melancholia',
        title: '"Melancholia" (exploitation du cheval)',
        author: 'Victor Hugo',
        year: '1856',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🐴',
        coverGradient: 'linear-gradient(135deg, #7060e7, #a696fe)',
        summary: "Poème des 'Contemplations' où Hugo dénonce l'exploitation des êtres faibles : enfants au travail et chevaux épuisés. Le cheval maltraité devient le symbole de toutes les victimes silencieuses de la société industrielle. Hugo défend la pitié envers les animaux comme extension de la justice sociale.",
        examTip: "Utilise Hugo pour lier la cause animale à la justice sociale : défendre les animaux, c'est défendre tous les opprimés. Hugo = compassion universelle.",
        keyQuote: ''
    },
    {
        id: 'joncour-chien-loup',
        title: 'Chien-loup',
        author: 'Serge Joncour',
        year: '2018',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '🐺',
        coverGradient: 'linear-gradient(135deg, #6858d8, #9f90ef)',
        summary: "Un couple parisien loue une maison isolée dans le Lot. Ils y rencontrent un étrange chien-loup et découvrent l'histoire d'un dompteur de fauves allemand pendant la Première Guerre mondiale. Le roman explore la frontière entre domestique et sauvage, entre civilisation et nature brute.",
        examTip: "Utilise cette oeuvre pour questionner la frontière entre le domestique et le sauvage, entre l'animal apprivoisé et la bête libre. Argument sur l'hybridité chien/loup.",
        keyQuote: ''
    },
    {
        id: 'kafka-metamorphose',
        title: 'La Métamorphose',
        author: 'Franz Kafka',
        year: '1915',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '🪲',
        coverGradient: 'linear-gradient(135deg, #5f4fd8, #9b8bef)',
        summary: "Gregor Samsa se réveille un matin transformé en insecte monstrueux. Sa famille, d'abord horrifiée, finit par le rejeter et le laisser mourir. Kafka explore la déshumanisation, le rejet de l'autre et la question : que reste-t-il d'humain quand on a un corps animal ? La frontière humain/animal est abolie.",
        examTip: "Utilise Kafka pour la question de la frontière humain/animal et la déshumanisation. La métamorphose = perdre son humanité aux yeux des autres. Oeuvre incontournable.",
        keyQuote: "« Un matin, au sortir d'un rêve agité, Gregor Samsa se retrouva dans son lit, métamorphosé en un monstrueux insecte. »"
    },
    {
        id: 'kessel-lion',
        title: 'Le Lion',
        author: 'Joseph Kessel',
        year: '1958',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🦁',
        coverGradient: 'linear-gradient(135deg, #7565e8, #ab9bff)',
        summary: "Au Kenya, une petite fille, Patricia, entretient un lien extraordinaire avec King, un lion sauvage. Ce lien fusionnel est menacé par le monde des adultes et les règles de la réserve. Kessel raconte la beauté et la fragilité de la relation entre un enfant et un animal sauvage, au-delà de la raison.",
        examTip: "Utilise Kessel pour illustrer le lien affectif pur entre l'enfant et l'animal sauvage, avant que la société n'impose ses règles. L'innocence vs la domestication.",
        keyQuote: ''
    },
    {
        id: 'kundera-karenine',
        title: "L'Insoutenable légèreté de l'être (7e partie « Le sourire de Karénine »)",
        author: 'Milan Kundera',
        year: '1984',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'difficile',
        diffLabel: 'Difficile',
        icon: '🐕',
        coverGradient: 'linear-gradient(135deg, #5545c8, #9585df)',
        summary: "La 7e partie du roman est consacrée à Karénine, la chienne de Tereza et Tomas. Kundera y développe une réflexion philosophique sur l'amour désintéressé : l'amour entre un humain et son animal est le seul amour pur, sans calcul ni possession. La mort de Karénine est l'une des scènes les plus émouvantes de la littérature.",
        examTip: "Utilise Kundera pour argumenter que l'amour homme-animal est un amour pur et désintéressé, plus authentique que l'amour humain. Citation très forte pour une dissertation.",
        keyQuote: "« L'amour entre l'homme et le chien est un amour idyllique. C'est un amour sans conflit, sans scènes déchirantes, sans évolution. »"
    },
    {
        id: 'la-fontaine-fables',
        title: 'Fables',
        author: 'Jean de La Fontaine',
        year: '1668-1694',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🦊',
        coverGradient: 'linear-gradient(135deg, #7f6ff8, #b5a8ff)',
        summary: "Les fables les plus célèbres de la littérature française. La Fontaine utilise des animaux (renard, loup, agneau, cigale, fourmi) pour donner des leçons de morale et critiquer la société du XVIIe siècle. Chaque animal incarne un trait humain : la ruse, la force, la naïveté. Le fondement de l'anthropomorphisme littéraire en France.",
        examTip: "Utilise La Fontaine comme référence absolue de l'anthropomorphisme en littérature française. Chaque fable = une leçon sur la nature humaine vue à travers les animaux.",
        keyQuote: "« La raison du plus fort est toujours la meilleure. »"
    },
    {
        id: 'london-croc-blanc',
        title: 'Croc-Blanc',
        author: 'Jack London',
        year: '1906',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🐺',
        coverGradient: 'linear-gradient(135deg, #6c5cd8, #a39bef)',
        summary: "Un loup-chien hybride naît dans le Grand Nord sauvage, est capturé, maltraité par des humains cruels, puis finalement adopté par un maître bienveillant. Le parcours inverse de 'L'Appel de la forêt' : de la sauvagerie vers la domestication. London explore la tension entre instinct animal et lien affectif avec l'homme.",
        examTip: "Utilise London pour la question nature vs domestication et l'idée que l'animal peut être transformé par la violence ou la bienveillance humaine.",
        keyQuote: ''
    },
    {
        id: 'martin-croire-fauves',
        title: 'Croire aux fauves',
        author: 'Nastassja Martin',
        year: '2019',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '🐻',
        coverGradient: 'linear-gradient(135deg, #7060d8, #a797ef)',
        summary: "Récit autobiographique : l'anthropologue Nastassja Martin est attaquée par un ours au Kamtchatka. Après cette rencontre violente, elle se sent transformée, « entre-deux » : ni tout à fait humaine, ni tout à fait autre. Le livre explore la frontière entre humain et animal à travers une expérience physique réelle et traumatique.",
        examTip: "Utilise cette oeuvre pour parler de la rencontre brutale avec l'animal sauvage et de la dissolution de la frontière humain/animal. Récit vécu, très puissant.",
        keyQuote: ''
    },
    {
        id: 'maupassant-coco',
        title: '"Coco"',
        author: 'Guy de Maupassant',
        year: '1884',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🐎',
        coverGradient: 'linear-gradient(135deg, #8878f8, #c0b5ff)',
        summary: "Nouvelle courte et cruelle : Coco est un vieux cheval devenu inutile. Un garçon de ferme le maltraite, le prive de nourriture et le laisse mourir de faim par sadisme. Maupassant dénonce la cruauté gratuite envers les animaux « inutiles » et la banalité du mal dans le monde rural.",
        examTip: "Utilise 'Coco' pour dénoncer la cruauté envers les animaux devenus « inutiles ». Texte court, facile à citer, impact émotionnel fort.",
        keyQuote: ''
    },
    {
        id: 'melville-moby-dick',
        title: 'Moby Dick',
        author: 'Herman Melville',
        year: '1851',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'difficile',
        diffLabel: 'Difficile',
        icon: '🐋',
        coverGradient: 'linear-gradient(135deg, #5848c8, #9888df)',
        summary: "Le capitaine Achab poursuit obsessionnellement Moby Dick, une baleine blanche gigantesque qui lui a arraché une jambe. La baleine incarne la nature indomptable, l'absolu, l'altérité radicale. C'est la folie de l'homme qui veut dominer ce qui le dépasse. Roman-fleuve monumental sur l'affrontement homme-animal.",
        examTip: "Utilise Moby Dick pour illustrer la folie humaine de vouloir dominer la nature. La baleine = symbole de l'altérité animale indomptable et de la nature qui résiste.",
        keyQuote: ''
    },
    {
        id: 'merle-animal-doue-raison',
        title: 'Un animal doué de raison',
        author: 'Robert Merle',
        year: '1967',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '🐬',
        coverGradient: 'linear-gradient(135deg, #6555d8, #9c8cef)',
        summary: "Roman de science-fiction où des dauphins apprennent à parler anglais grâce à un scientifique. L'armée américaine veut les utiliser comme armes. Le titre est ironique : qui est « l'animal doué de raison » ? L'humain qui instrumentalise, ou le dauphin intelligent et pacifique ? Le roman questionne notre définition de l'intelligence.",
        examTip: "Utilise Merle pour questionner la hiérarchie des intelligences : le dauphin qui parle est-il plus « raisonnable » que l'humain qui fait la guerre ? Argument antispéciste fort.",
        keyQuote: ''
    },
    {
        id: 'orwell-ferme-animaux',
        title: 'La Ferme des animaux',
        author: 'George Orwell',
        year: '1945',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🐖',
        coverGradient: 'linear-gradient(135deg, #7363e8, #a999ff)',
        summary: "Les animaux d'une ferme chassent le fermier et instaurent une société égalitaire. Mais les cochons prennent le pouvoir et deviennent des tyrans pires que les humains. Allégorie du totalitarisme soviétique. Orwell montre que l'utopie animale sert de miroir aux dérives politiques humaines.",
        examTip: "Utilise Orwell pour montrer que les animaux servent d'allégorie politique. La fable animalière comme outil de critique du totalitarisme. Citation culte à retenir.",
        keyQuote: "« Tous les animaux sont égaux, mais certains sont plus égaux que d'autres. »"
    },
    {
        id: 'ovide-metamorphoses',
        title: 'Les Métamorphoses',
        author: 'Ovide',
        year: 'Ier siècle',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '🦌',
        coverGradient: 'linear-gradient(135deg, #8070e8, #b6a9ff)',
        summary: "Poème mythologique monumental : des centaines de récits de transformations entre humains, animaux et végétaux. Arachné en araignée, Actéon en cerf, Io en vache... Chez Ovide, la frontière humain/animal n'existe pas : tout est métamorphose, tout est fluide. Texte fondateur de la pensée sur l'hybridité des formes vivantes.",
        examTip: "Utilise Ovide pour montrer que dans la mythologie, la frontière humain/animal est fluide. Les métamorphoses = porosité entre les règnes du vivant.",
        keyQuote: ''
    },
    {
        id: 'page-animaux-comestibles',
        title: 'Les animaux ne sont pas comestibles',
        author: 'Martin Page',
        year: '2017',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🌱',
        coverGradient: 'linear-gradient(135deg, #7b6bf8, #b1a4ff)',
        summary: "Récit autobiographique où Martin Page raconte sa conversion au véganisme. Il explique avec humour et sincérité pourquoi il a cessé de manger les animaux. Le livre est aussi un plaidoyer pour repenser notre rapport aux animaux au quotidien : alimentation, vêtements, divertissements.",
        examTip: "Utilise Martin Page pour un argument concret et contemporain sur le véganisme et la remise en question de l'exploitation animale quotidienne.",
        keyQuote: ''
    },
    {
        id: 'ponge-parti-pris',
        title: 'Le Parti pris des choses',
        author: 'Francis Ponge',
        year: '1942',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'difficile',
        diffLabel: 'Difficile',
        icon: '🦐',
        coverGradient: 'linear-gradient(135deg, #6252c8, #9e8edf)',
        summary: "Recueil de poèmes en prose où Ponge décrit des objets et des animaux (l'huître, la crevette, l'escargot) avec une précision quasi scientifique. L'objectif : prendre le « parti pris des choses », c'est-à-dire adopter le point de vue de l'objet ou de l'animal. Une poésie qui refuse l'anthropocentrisme et donne dignité aux êtres les plus humbles.",
        examTip: "Utilise Ponge pour montrer une approche poétique anti-anthropocentrique : décrire l'animal tel qu'il est, pas tel qu'on le projette. Le regard poétique comme respect.",
        keyQuote: ''
    },
    {
        id: 'roubaud-animaux-monde',
        title: 'Les Animaux de tout le monde',
        author: 'Jacques Roubaud',
        year: '1983',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🐈',
        coverGradient: 'linear-gradient(135deg, #8575e8, #bbb0ff)',
        summary: "Recueil de poèmes ludiques et accessibles, chacun consacré à un animal différent. Roubaud mêle humour, tendresse et jeux de langage pour dresser un bestiaire poétique. Les poèmes sont courts, amusants et faciles à retenir. Parfait pour montrer que la poésie peut parler des animaux avec légèreté et intelligence.",
        examTip: "Utilise Roubaud pour un exemple de poésie contemporaine accessible sur les animaux. Bon pour varier les registres dans une dissertation (humour + poésie).",
        keyQuote: ''
    },
    {
        id: 'suskind-pigeon',
        title: 'Le Pigeon',
        author: 'Patrick Süskind',
        year: '1987',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🐦',
        coverGradient: 'linear-gradient(135deg, #7868d8, #af9fef)',
        summary: "Court récit : un vigile parisien maniaque de l'ordre voit sa vie basculer quand un pigeon s'installe devant sa porte. Cet événement insignifiant provoque une crise existentielle totale. Süskind montre comment un simple animal peut révéler la fragilité de nos certitudes et de notre besoin de contrôle.",
        examTip: "Utilise Süskind pour montrer que la présence animale, même banale, peut bouleverser l'ordre humain. Le pigeon = l'irruption de l'imprévu animal dans nos vies.",
        keyQuote: ''
    },
    {
        id: 'schimmelpfennig-royaume-animaux',
        title: 'Le Royaume des animaux',
        author: 'Roland Schimmelpfennig',
        year: '2022',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '🎭',
        coverGradient: 'linear-gradient(135deg, #6d5dd8, #a494ef)',
        summary: "Pièce de théâtre contemporaine qui met en scène la rencontre entre le monde humain et le monde animal. Schimmelpfennig brouille les frontières entre les espèces et interroge ce que signifie être humain quand les animaux réclament leur place. Un texte théâtral original qui questionne la cohabitation des règnes.",
        examTip: "Utilise cette pièce pour un exemple théâtral contemporain sur la cohabitation humain/animal. Bon pour varier les genres littéraires dans une copie.",
        keyQuote: ''
    },
    {
        id: 'vercors-animaux-denatures',
        title: 'Les Animaux dénaturés',
        author: 'Vercors',
        year: '1952',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '🧬',
        coverGradient: 'linear-gradient(135deg, #7262d8, #a898ef)',
        summary: "On découvre des « tropis », créatures mi-singes mi-humaines. Un journaliste tue volontairement un tropi pour forcer un procès : est-ce un meurtre ou l'abattage d'un animal ? Le roman pose la question fondamentale : où commence l'humain et où finit l'animal ? Qu'est-ce qui définit l'humanité ?",
        examTip: "Utilise Vercors pour la question clé de la frontière humain/animal. Si on ne sait pas définir l'humain, comment justifier le traitement des animaux ? Argument philosophique central.",
        keyQuote: ''
    },
    {
        id: 'zola-la-terre',
        title: 'La Terre',
        author: 'Émile Zola',
        year: '1887',
        category: 'litterature',
        categoryLabel: 'Littérature',
        difficulty: 'difficile',
        diffLabel: 'Difficile',
        icon: '🌾',
        coverGradient: 'linear-gradient(135deg, #5e4ec8, #9a8adf)',
        summary: "Roman naturaliste sur la paysannerie française au XIXe siècle. Zola décrit crûment la vie rurale où humains et animaux partagent le même espace, les mêmes souffrances, la même brutalité. Les animaux de ferme sont omniprésents : leur traitement reflète la violence des rapports sociaux. Le corps animal et le corps humain sont traités de façon parallèle.",
        examTip: "Utilise Zola pour montrer la proximité corps humain / corps animal dans le monde rural et la violence partagée. Approche naturaliste = description crue de la condition animale.",
        keyQuote: ''
    },

    // ==================== ESSAIS (13 oeuvres) ====================

    {
        id: 'buffon-discours-nature',
        title: '"Discours sur la nature des animaux"',
        author: 'Buffon',
        year: '1753',
        category: 'essai',
        categoryLabel: 'Essai',
        difficulty: 'difficile',
        diffLabel: 'Difficile',
        icon: '🔬',
        coverGradient: 'linear-gradient(135deg, #0984e3, #74b9ff)',
        summary: "Buffon, naturaliste des Lumières, affirme dans son 'Histoire naturelle' que les animaux sont des machines sans âme ni raison. Pour lui, l'animal agit par instinct, pas par intelligence. Position cartésienne influente qui a longtemps justifié la domination humaine sur les animaux.",
        examTip: "Utilise Buffon comme représentant de la thèse de l'animal-machine. Position à nuancer et contredire avec des auteurs modernes. Utile comme antithèse.",
        keyQuote: ''
    },
    {
        id: 'condillac-traite-animaux',
        title: 'Traité des animaux',
        author: 'Condillac',
        year: '1755',
        category: 'essai',
        categoryLabel: 'Essai',
        difficulty: 'difficile',
        diffLabel: 'Difficile',
        icon: '🧠',
        coverGradient: 'linear-gradient(135deg, #0b7dda, #6bb0f6)',
        summary: "Condillac s'oppose à Buffon et à Descartes : il affirme que les animaux ont des sensations, de la mémoire, et même une forme d'intelligence. Ils ne sont pas des machines. C'est un texte fondateur pour la reconnaissance de la sensibilité animale, écrit au coeur des Lumières.",
        examTip: "Utilise Condillac comme contre-argument à l'animal-machine : les animaux sentent, mémorisent, pensent à leur niveau. Un philosophe des Lumières qui défend la sensibilité animale.",
        keyQuote: ''
    },
    {
        id: 'deleuze-abecedaire-animal',
        title: '"A comme animal" (L\'Abécédaire)',
        author: 'Gilles Deleuze',
        year: '1988',
        category: 'essai',
        categoryLabel: 'Essai',
        difficulty: 'difficile',
        diffLabel: 'Difficile',
        icon: '🎬',
        coverGradient: 'linear-gradient(135deg, #0a70cc, #5da3ed)',
        summary: "Dans cet entretien filmé, Deleuze parle de son rapport aux animaux. Il critique les gens qui parlent à leur chien comme à un bébé et préfère penser l'animal par son « territoire » et ses « affects ». Pour Deleuze, comprendre un animal, c'est comprendre son monde propre, pas le réduire au nôtre.",
        examTip: "Utilise Deleuze pour critiquer l'anthropomorphisme sentimental et proposer une approche qui respecte le monde propre de l'animal. Concept clé : le « devenir-animal ».",
        keyQuote: ''
    },
    {
        id: 'derrida-animal-donc-je-suis',
        title: "L'Animal que donc je suis",
        author: 'Jacques Derrida',
        year: '2006',
        category: 'essai',
        categoryLabel: 'Essai',
        difficulty: 'difficile',
        diffLabel: 'Difficile',
        icon: '🐱',
        coverGradient: 'linear-gradient(135deg, #0867c0, #4f97e4)',
        summary: "Derrida, nu devant son chat, se demande : que voit le chat ? L'animal me regarde et ce regard me trouble. Le philosophe remet en question toute la tradition occidentale qui réduit l'animal à un objet. Le mot « animal » lui-même est violent car il met toutes les espèces dans le même sac. Texte fondateur de la pensée contemporaine sur l'animalité.",
        examTip: "Utilise Derrida pour la remise en question du mot « animal » et l'idée que le regard animal nous déstabilise. Argument philosophique de haut niveau, très valorisé à l'examen.",
        keyQuote: "« L'animal nous regarde, et nous sommes nus devant lui. »"
    },
    {
        id: 'fontenay-silence-betes',
        title: 'Le Silence des bêtes',
        author: 'Élisabeth de Fontenay',
        year: '1998',
        category: 'essai',
        categoryLabel: 'Essai',
        difficulty: 'difficile',
        diffLabel: 'Difficile',
        icon: '📚',
        coverGradient: 'linear-gradient(135deg, #0d8df0, #7ec0ff)',
        summary: "Somme philosophique monumentale qui retrace toute l'histoire de la pensée occidentale sur les animaux, d'Aristote à nos jours. Fontenay montre comment la philosophie a systématiquement réduit l'animal au silence. C'est LA référence académique sur la question animale en philosophie.",
        examTip: "Utilise Fontenay comme référence savante et panoramique sur la pensée animale dans l'histoire de la philosophie. Impressionne le correcteur si bien utilisé.",
        keyQuote: ''
    },
    {
        id: 'goodall-chimpanzes',
        title: 'Ma vie avec les chimpanzés',
        author: 'Jane Goodall',
        year: '1988',
        category: 'essai',
        categoryLabel: 'Essai',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🐒',
        coverGradient: 'linear-gradient(135deg, #1196f3, #82c9ff)',
        summary: "Jane Goodall raconte ses 30 ans passés auprès des chimpanzés en Tanzanie. Elle a révolutionné la science en montrant que les chimpanzés utilisent des outils, ont des émotions, des personnalités individuelles et des liens sociaux complexes. Son travail a bouleversé la frontière entre humain et animal.",
        examTip: "Utilise Goodall pour des arguments scientifiques concrets : les chimpanzés ont des émotions, utilisent des outils, ont une culture. Preuve que la frontière humain/animal est poreuse.",
        keyQuote: ''
    },
    {
        id: 'harchi-ainsi-animal',
        title: "Ainsi l'animal et nous",
        author: 'Kaoutar Harchi',
        year: '2024',
        category: 'essai',
        categoryLabel: 'Essai',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '✍️',
        coverGradient: 'linear-gradient(135deg, #0f8de6, #78bcfc)',
        summary: "Essai contemporain qui explore les liens entre la domination des animaux et d'autres formes de domination (racisme, sexisme, colonialisme). Harchi montre que l'exploitation animale est liée aux mêmes structures de pouvoir que l'oppression des humains. Une approche intersectionnelle de la question animale.",
        examTip: "Utilise Harchi pour lier la question animale aux autres luttes sociales (intersectionnalité). Argument contemporain et original : domination animale = domination sociale.",
        keyQuote: ''
    },
    {
        id: 'jeangene-vilmer-ethique-animale',
        title: "L'Éthique animale",
        author: 'Jean-Baptiste Jeangène Vilmer',
        year: '2008',
        category: 'essai',
        categoryLabel: 'Essai',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '⚖️',
        coverGradient: 'linear-gradient(135deg, #0a7ad5, #6aacf2)',
        summary: "Manuel de référence qui présente toutes les positions philosophiques sur les droits des animaux : utilitarisme (Singer), déontologie (Regan), abolitionnisme, welfarisme... Jeangène Vilmer fait le tour de la question de façon claire et structurée. Indispensable pour comprendre les enjeux du débat éthique contemporain.",
        examTip: "Utilise cet essai pour structurer ton argumentation éthique : il présente tous les courants de pensée sur les droits animaux. Très utile pour une partie « arguments philosophiques ».",
        keyQuote: ''
    },
    {
        id: 'lorenz-trois-essais',
        title: 'Trois essais sur le comportement animal et humain',
        author: 'Konrad Lorenz',
        year: '1965',
        category: 'essai',
        categoryLabel: 'Essai',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '🪿',
        coverGradient: 'linear-gradient(135deg, #0c85e0, #70b5f8)',
        summary: "Lorenz, prix Nobel, fondateur de l'éthologie (étude du comportement animal), montre les parallèles entre comportements animaux et humains. Ses recherches sur les oies cendrées (l'empreinte) et l'agressivité ont révolutionné notre compréhension de l'instinct. Il prouve que la frontière entre comportement animal et humain est mince.",
        examTip: "Utilise Lorenz pour des arguments scientifiques sur la proximité comportementale homme/animal. L'éthologie prouve que nos comportements ont des racines animales.",
        keyQuote: ''
    },
    {
        id: 'montaigne-apologie-sebond',
        title: 'Essais, livre II, "Apologie de Raymond Sebond"',
        author: 'Montaigne',
        year: '1580',
        category: 'essai',
        categoryLabel: 'Essai',
        difficulty: 'difficile',
        diffLabel: 'Difficile',
        icon: '🪶',
        coverGradient: 'linear-gradient(135deg, #0760b8, #4890db)',
        summary: "Montaigne y démonte la prétendue supériorité humaine : « Quand je joue avec ma chatte, qui sait si elle ne s'amuse pas de moi plus que moi d'elle ? » Il montre que les animaux ont des émotions, de l'intelligence et des compétences que les humains n'ont pas. Texte fondateur de l'humilité face à l'animal.",
        examTip: "Utilise Montaigne comme référence classique contre l'anthropocentrisme. La citation sur la chatte est LA citation à connaître par coeur pour l'examen.",
        keyQuote: "« Quand je joue avec ma chatte, qui sait si elle ne s'amuse pas de moi plus que moi d'elle ? »"
    },
    {
        id: 'pastoureau-ours',
        title: "L'Ours. Histoire d'un roi déchu",
        author: 'Michel Pastoureau',
        year: '2007',
        category: 'essai',
        categoryLabel: 'Essai',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '🐻',
        coverGradient: 'linear-gradient(135deg, #1090e8, #7cbdff)',
        summary: "L'historien Pastoureau raconte comment l'ours, roi des animaux en Europe pendant des millénaires, a été détrôné par le lion au Moyen Âge sous l'influence de l'Église. L'ours, trop proche de l'homme (il se tient debout, il aime le miel), faisait peur au clergé. Un livre passionnant sur l'histoire culturelle des animaux.",
        examTip: "Utilise Pastoureau pour montrer que la hiérarchie des animaux est une construction culturelle et religieuse, pas un fait naturel. L'ours détrôné par le lion = politique du symbole.",
        keyQuote: ''
    },
    {
        id: 'vauclair-intelligence-animal',
        title: "L'Intelligence de l'animal",
        author: 'Jacques Vauclair',
        year: '1995',
        category: 'essai',
        categoryLabel: 'Essai',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '🧩',
        coverGradient: 'linear-gradient(135deg, #0e88e3, #76b8fa)',
        summary: "Ouvrage de psychologie cognitive animale qui démontre que de nombreuses espèces possèdent des capacités intellectuelles complexes : résolution de problèmes, communication, mémoire, conscience de soi. Vauclair prouve scientifiquement que l'intelligence n'est pas un monopole humain.",
        examTip: "Utilise Vauclair pour des preuves scientifiques de l'intelligence animale. Argument fort contre l'idée que seuls les humains « pensent ».",
        keyQuote: ''
    },
    {
        id: 'voltaire-betes',
        title: 'Article "Bêtes" (Dictionnaire philosophique)',
        author: 'Voltaire',
        year: '1764',
        category: 'essai',
        categoryLabel: 'Essai',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '📜',
        coverGradient: 'linear-gradient(135deg, #0b80d8, #6cb2f4)',
        summary: "Voltaire s'attaque à la thèse de l'animal-machine de Descartes avec ironie et vigueur. Il affirme que les animaux souffrent, sentent et comprennent. Leur couper la gorge en affirmant qu'ils ne sentent rien est une absurdité cruelle. Un plaidoyer des Lumières pour la reconnaissance de la souffrance animale.",
        examTip: "Utilise Voltaire pour réfuter l'animal-machine avec style. Sa critique de Descartes est percutante et facile à citer. Voltaire = ironie au service de la compassion animale.",
        keyQuote: "« Des barbares saisissent ce chien [...] Réponds-moi, machiniste, la nature a-t-elle arrangé tous les ressorts du sentiment dans cet animal afin qu'il ne sente pas ? »"
    },

    // ==================== FILMS (9 oeuvres) ====================

    {
        id: 'bresson-balthazar',
        title: 'Au hasard Balthazar',
        author: 'Robert Bresson',
        year: '1966',
        category: 'film',
        categoryLabel: 'Film',
        difficulty: 'difficile',
        diffLabel: 'Difficile',
        icon: '🫏',
        coverGradient: 'linear-gradient(135deg, #d63031, #ff7675)',
        summary: "Film qui suit la vie d'un âne, Balthazar, de sa naissance à sa mort. Il passe de maître en maître, subissant la cruauté, l'indifférence et parfois la tendresse des humains. L'âne est un témoin silencieux de la méchanceté humaine. Considéré comme un chef-d'oeuvre du cinéma, le film donne à l'animal une dimension christique.",
        examTip: "Utilise Bresson pour montrer que le cinéma peut donner une dimension sacrée à l'animal. L'âne comme figure de l'innocence martyrisée par les humains.",
        keyQuote: ''
    },
    {
        id: 'caillet-regne-animal',
        title: 'Le Règne animal',
        author: 'Thomas Cailley',
        year: '2023',
        category: 'film',
        categoryLabel: 'Film',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '🦅',
        coverGradient: 'linear-gradient(135deg, #c0392b, #f56b6b)',
        summary: "Film de science-fiction français où des humains se transforment progressivement en animaux (une femme devient oiseau, un homme devient ours...). La société doit apprendre à cohabiter avec ces « nouveaux animaux ». Le film interroge la frontière entre humain et animal et la peur de l'autre. Succès public et critique en 2023.",
        examTip: "Utilise ce film pour parler de l'hybridité humain/animal et de l'acceptation de l'altérité. Très contemporain, les correcteurs le connaissent probablement.",
        keyQuote: ''
    },
    {
        id: 'dion-animal',
        title: 'Animal',
        author: 'Cyril Dion',
        year: '2021',
        category: 'film',
        categoryLabel: 'Film',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🌍',
        coverGradient: 'linear-gradient(135deg, #e74c3c, #ff8a80)',
        summary: "Documentaire où deux adolescents partent à la rencontre de la biodiversité menacée dans le monde. Ils découvrent la sixième extinction de masse et cherchent des solutions. Dion montre que nous faisons partie du vivant et que notre survie dépend de celle des autres espèces. Film engagé et accessible.",
        examTip: "Utilise ce documentaire pour des chiffres concrets sur la perte de biodiversité et l'argument écologique : protéger les animaux = protéger l'humanité.",
        keyQuote: ''
    },
    {
        id: 'franju-sang-betes',
        title: 'Le Sang des bêtes',
        author: 'Georges Franju',
        year: '1949',
        category: 'film',
        categoryLabel: 'Film',
        difficulty: 'difficile',
        diffLabel: 'Difficile',
        icon: '🩸',
        coverGradient: 'linear-gradient(135deg, #b71c1c, #ef5350)',
        summary: "Documentaire choc tourné dans les abattoirs parisiens de Vaugirard et La Villette. Franju filme crûment la mise à mort des animaux, sans commentaire moralisateur. La beauté formelle du film contraste avec la violence des images. Un film fondateur pour la critique de l'abattage industriel, encore bouleversant aujourd'hui.",
        examTip: "Utilise Franju pour dénoncer la réalité cachée des abattoirs. Le film rend visible ce qu'on ne veut pas voir. Argument sur l'invisibilisation de la souffrance animale.",
        keyQuote: ''
    },
    {
        id: 'herzog-grizzly-man',
        title: 'Grizzly Man',
        author: 'Werner Herzog',
        year: '2005',
        category: 'film',
        categoryLabel: 'Film',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '🐻',
        coverGradient: 'linear-gradient(135deg, #d32f2f, #ff6659)',
        summary: "Documentaire sur Timothy Treadwell, un homme qui a vécu 13 étés parmi les grizzlys d'Alaska avant d'être dévoré par l'un d'eux. Herzog montre la fascination et l'illusion de Treadwell qui croyait être « ami » avec les ours. Le film questionne notre fantasme de communion avec la nature sauvage et ses limites mortelles.",
        examTip: "Utilise ce film pour montrer les limites de l'anthropomorphisme : projeter nos sentiments sur les animaux sauvages peut être fatal. La nature n'est pas un conte de fées.",
        keyQuote: ''
    },
    {
        id: 'microcosmos',
        title: 'Microcosmos',
        author: 'Claude Nuridsany & Marie Pérennou',
        year: '1996',
        category: 'film',
        categoryLabel: 'Film',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🐛',
        coverGradient: 'linear-gradient(135deg, #e53935, #ff8a80)',
        summary: "Documentaire poétique filmé en gros plan dans une prairie française. On découvre le monde minuscule des insectes, escargots, araignées avec une beauté stupéfiante. Sans narration, le film laisse les images parler. Il révèle un univers animal invisible à l'oeil nu, aussi riche et complexe que le nôtre.",
        examTip: "Utilise Microcosmos pour montrer que les animaux les plus petits et méprisés ont un monde fascinant. Argument contre la hiérarchie entre espèces « nobles » et « inférieures ».",
        keyQuote: ''
    },
    {
        id: 'perrin-peuple-migrateur',
        title: 'Le Peuple migrateur',
        author: 'Jacques Perrin',
        year: '2001',
        category: 'film',
        categoryLabel: 'Film',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🦢',
        coverGradient: 'linear-gradient(135deg, #dc3545, #ff9090)',
        summary: "Documentaire spectaculaire qui suit les oiseaux migrateurs dans leurs voyages autour du monde. Filmé au plus près des oiseaux en vol, le film offre une immersion totale dans leur univers. Les oiseaux ne connaissent pas de frontières : le film montre un monde animal libre et sans limites géographiques.",
        examTip: "Utilise Le Peuple migrateur pour illustrer la liberté animale et l'idée que les animaux ignorent les frontières humaines. Belles images, argument sur la liberté naturelle.",
        keyQuote: ''
    },
    {
        id: 'zilbalodis-flow',
        title: 'Flow',
        author: 'Gints Zilbalodis',
        year: '2024',
        category: 'film',
        categoryLabel: 'Film',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🐈',
        coverGradient: 'linear-gradient(135deg, #cb2d3e, #ef473a)',
        summary: "Film d'animation letton sans dialogue où un chat solitaire, dans un monde post-apocalyptique sans humains, rejoint un groupe d'animaux (chien, capybara, oiseau, lémurien) sur un bateau. Ensemble, ils traversent un monde submergé. Le film montre la solidarité inter-espèces et la résilience animale sans aucune intervention humaine.",
        examTip: "Utilise Flow pour imaginer un monde sans humains où les animaux s'organisent entre eux. Film récent, primé, original : parfait pour une ouverture contemporaine.",
        keyQuote: ''
    },
    {
        id: 'cartoons-americains',
        title: 'Cartoons américains (figuration animale)',
        author: 'Cartoons américains',
        year: 'XXe siècle',
        category: 'film',
        categoryLabel: 'Film',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🐭',
        coverGradient: 'linear-gradient(135deg, #e84351, #ff9a9e)',
        summary: "De Mickey Mouse à Tom et Jerry, les cartoons américains ont créé un bestiaire populaire universel. Les animaux y sont totalement humanisés : ils parlent, s'habillent, vivent dans des maisons. Cette tradition d'anthropomorphisme de masse influence notre perception des animaux depuis l'enfance. L'animal cartoon = projection totale de l'humain.",
        examTip: "Utilise les cartoons pour parler de l'anthropomorphisme de masse dans la culture populaire. Exemple accessible que tout le monde connaît. Bon pour montrer la différence entre animal réel et animal fantasmé.",
        keyQuote: ''
    },

    // ==================== BD (2 oeuvres) ====================

    {
        id: 'rochette-loup-derniere-reine',
        title: 'Le Loup / La Dernière Reine',
        author: 'Jean-Marc Rochette',
        year: '2019 / 2022',
        category: 'bd',
        categoryLabel: 'BD',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🐺',
        coverGradient: 'linear-gradient(135deg, #00b894, #55efc4)',
        summary: "Dans 'Le Loup', un berger et un loup s'affrontent toute leur vie dans les Alpes. Dans 'La Dernière Reine', un peintre tente de sauver le dernier ours des Alpes. Rochette, lui-même montagnard, dessine la beauté sauvage et la violence de la cohabitation homme/animal dans les montagnes. Des BD magnifiques et profondes.",
        examTip: "Utilise Rochette pour la cohabitation conflictuelle homme/animal sauvage en montagne. La BD comme art à part entière pour traiter de la question animale.",
        keyQuote: ''
    },
    {
        id: 'stassen-deogratias',
        title: 'Déogratias',
        author: 'Jean-Philippe Stassen',
        year: '2000',
        category: 'bd',
        categoryLabel: 'BD',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '🐕',
        coverGradient: 'linear-gradient(135deg, #00a884, #45deb4)',
        summary: "BD sur le génocide rwandais. Déogratias, un jeune Hutu traumatisé, se transforme mentalement en chien après avoir participé aux massacres. La bestialisation est ici double : les Tutsis sont traités de « cafards » par les génocidaires, et le bourreau lui-même perd son humanité. L'animalisation comme arme et comme conséquence de la violence extrême.",
        examTip: "Utilise Déogratias pour montrer la bestialisation comme arme du génocide (traiter l'autre de « cafard ») et comme résultat du trauma. Lien puissant entre violence et animalisation.",
        keyQuote: ''
    },

    // ==================== ARTS PLASTIQUES (11 oeuvres) ====================

    {
        id: 'bestiaires-medievaux',
        title: 'Bestiaires médiévaux',
        author: 'Anonymes médiévaux',
        year: 'XIIe-XIIIe siècle',
        category: 'art',
        categoryLabel: 'Art plastique',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🦄',
        coverGradient: 'linear-gradient(135deg, #f39c12, #ffeaa7)',
        summary: "Manuscrits enluminés qui décrivent des animaux réels et imaginaires (licorne, phénix, basilic) avec des significations morales et religieuses. Chaque animal est un symbole : le pélican = le sacrifice du Christ, le lion = la résurrection, le serpent = le péché. L'animal médiéval est un signe à déchiffrer, pas un être naturel.",
        examTip: "Utilise les bestiaires pour montrer que l'animal est un symbole moral et religieux au Moyen Âge. L'art animalier comme langage codé.",
        keyQuote: ''
    },
    {
        id: 'bonheur-rosa',
        title: 'Oeuvres de Rosa Bonheur',
        author: 'Rosa Bonheur',
        year: 'XIXe siècle',
        category: 'art',
        categoryLabel: 'Art plastique',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🐂',
        coverGradient: 'linear-gradient(135deg, #e67e22, #f9d88b)',
        summary: "Peintre animalière du XIXe siècle, Rosa Bonheur est célèbre pour ses tableaux monumentaux de chevaux, boeufs et cerfs ('Le Marché aux chevaux', 'Labourage nivernais'). Elle étudiait les animaux dans les abattoirs et les foires pour les peindre avec précision. Femme libre et pionnière, elle a imposé l'art animalier comme un genre majeur.",
        examTip: "Utilise Rosa Bonheur pour montrer que l'art animalier est un genre à part entière, porté par une femme indépendante. Argument pour la dignité de la représentation animale en peinture.",
        keyQuote: ''
    },
    {
        id: 'bonnard-chats',
        title: 'Les chats',
        author: 'Pierre Bonnard',
        year: 'Début XXe siècle',
        category: 'art',
        categoryLabel: 'Art plastique',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🐱',
        coverGradient: 'linear-gradient(135deg, #d4940e, #f5e59a)',
        summary: "Bonnard, peintre nabis puis intimiste, a peint des dizaines de chats dans ses scènes d'intérieur. Le chat est toujours là, sur la table, sur le lit, dans un coin. Chez Bonnard, le chat fait partie de l'intimité domestique, il est un compagnon silencieux et naturel de la vie quotidienne.",
        examTip: "Utilise Bonnard pour montrer l'animal comme compagnon intime du quotidien. Le chat dans la peinture = présence discrète et familière de l'animal dans nos vies.",
        keyQuote: ''
    },
    {
        id: 'bourgeois-maman',
        title: 'Maman',
        author: 'Louise Bourgeois',
        year: '1999',
        category: 'art',
        categoryLabel: 'Art plastique',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '🕷️',
        coverGradient: 'linear-gradient(135deg, #c88508, #edd87e)',
        summary: "Sculpture monumentale d'une araignée géante en bronze de 9 mètres de haut. Bourgeois associe l'araignée à sa mère : tisserande, protectrice, travailleuse. L'araignée, animal habituellement répugnant, devient un symbole d'amour maternel. L'oeuvre renverse nos préjugés sur les animaux « dégoûtants ».",
        examTip: "Utilise Bourgeois pour montrer comment l'art peut transformer notre regard sur un animal méprisé. L'araignée = mère protectrice. Renversement des préjugés.",
        keyQuote: ''
    },
    {
        id: 'chagall-animaux',
        title: 'Oeuvres de Marc Chagall',
        author: 'Marc Chagall',
        year: 'XXe siècle',
        category: 'art',
        categoryLabel: 'Art plastique',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🐐',
        coverGradient: 'linear-gradient(135deg, #f1a30e, #fbe7a0)',
        summary: "Chagall peuple ses tableaux oniriques de chèvres, ânes, coqs et poissons volants. Les animaux flottent dans le ciel, dansent avec les humains, se mêlent aux scènes de village. Chez Chagall, l'animal est un être poétique et spirituel, lié à la mémoire, au rêve et à la culture juive de son enfance en Biélorussie.",
        examTip: "Utilise Chagall pour montrer l'animal comme figure onirique et poétique dans l'art. Les animaux de Chagall = mémoire, rêve, monde intérieur.",
        keyQuote: ''
    },
    {
        id: 'chardin-la-raie',
        title: 'La Raie',
        author: 'Jean Siméon Chardin',
        year: '1728',
        category: 'art',
        categoryLabel: 'Art plastique',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '🐟',
        coverGradient: 'linear-gradient(135deg, #db9a08, #f3dc8a)',
        summary: "Nature morte célèbre montrant une raie écorchée, ouverte, pendue dans une cuisine. L'animal mort devient un spectacle troublant : la raie semble sourire, son intérieur est exposé crûment. Chardin transforme un animal de boucherie en une oeuvre qui interroge la frontière entre beauté et cruauté, entre nourriture et être vivant.",
        examTip: "Utilise Chardin pour montrer que l'art peut rendre visible la violence faite aux animaux même dans un genre « neutre » comme la nature morte. La raie = beauté du corps animal exposé.",
        keyQuote: ''
    },
    {
        id: 'le-brun-physiognomonie',
        title: 'Études physiognomoniques',
        author: 'Charles Le Brun',
        year: 'XVIIe siècle',
        category: 'art',
        categoryLabel: 'Art plastique',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '🦅',
        coverGradient: 'linear-gradient(135deg, #e8a10c, #f6e198)',
        summary: "Le Brun, premier peintre de Louis XIV, a réalisé des dessins comparant les visages humains et les faces animales. L'homme colérique ressemble au lion, le rusé au renard, le craintif au lièvre. La physiognomonie animale cherche l'animal dans l'homme et l'homme dans l'animal. Un projet fascinant sur l'hybridité des formes.",
        examTip: "Utilise Le Brun pour montrer la tradition de comparaison visages humains / faces animales. L'homme comme animal, l'animal comme miroir de l'homme. Lien homme-animal par le corps.",
        keyQuote: ''
    },
    {
        id: 'hokusai-saumon-souris',
        title: 'Saumon salé et souris / manga',
        author: 'Hokusai',
        year: 'XIXe siècle',
        category: 'art',
        categoryLabel: 'Art plastique',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🐭',
        coverGradient: 'linear-gradient(135deg, #f0a818, #f8e4a2)',
        summary: "Hokusai, maître de l'estampe japonaise, a dessiné des milliers d'animaux avec une précision et une vitalité extraordinaires. Son 'Saumon salé et souris' montre un animal humble avec autant de soin qu'un paysage grandiose. Ses 'manga' (carnets de croquis) contiennent des planches entières d'animaux. L'art japonais place l'animal au même niveau que l'humain.",
        examTip: "Utilise Hokusai pour montrer une vision non-occidentale de l'animal : dans l'art japonais, l'animal est un sujet à part entière, pas inférieur à l'homme.",
        keyQuote: ''
    },
    {
        id: 'liljefors-peinture',
        title: 'Oeuvres de Bruno Liljefors',
        author: 'Bruno Liljefors',
        year: 'Fin XIXe siècle',
        category: 'art',
        categoryLabel: 'Art plastique',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🦆',
        coverGradient: 'linear-gradient(135deg, #dea010, #f5e094)',
        summary: "Peintre animalier suédois considéré comme le meilleur peintre de la faune sauvage. Liljefors peint les animaux dans leur environnement naturel avec un réalisme saisissant : renards dans la neige, aigles en vol, lièvres dans les herbes. Il montre l'animal dans son monde, pas dans le nôtre.",
        examTip: "Utilise Liljefors pour un exemple de peinture animalière respectueuse : l'animal dans son milieu naturel, sans anthropomorphisme. L'art au service de l'observation du réel.",
        keyQuote: ''
    },
    {
        id: 'rousseau-douanier',
        title: 'Oeuvres du Douanier Rousseau',
        author: 'Henri Rousseau',
        year: 'Fin XIXe - début XXe siècle',
        category: 'art',
        categoryLabel: 'Art plastique',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🦁',
        coverGradient: 'linear-gradient(135deg, #d49610, #f0d888)',
        summary: "Le Douanier Rousseau peint des jungles luxuriantes peuplées de lions, singes, serpents et oiseaux exotiques, sans avoir jamais quitté la France. Ses animaux sont fantasmés, issus de visites au Jardin des Plantes et de livres illustrés. Rousseau = l'animal rêvé, imaginé, une jungle intérieure plus qu'une réalité.",
        examTip: "Utilise Rousseau pour montrer l'animal comme projection de l'imaginaire humain. Ses jungles = la nature fantasmée, pas observée. Argument sur l'animal rêvé vs l'animal réel.",
        keyQuote: ''
    },
    {
        id: 'lascaux-fresques',
        title: 'Fresques de Lascaux',
        author: 'Artistes du Paléolithique',
        year: 'Environ 17 000 ans av. J.-C.',
        category: 'art',
        categoryLabel: 'Art plastique',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🦌',
        coverGradient: 'linear-gradient(135deg, #cf9012, #ecce80)',
        summary: "Les premières oeuvres d'art de l'humanité représentent des animaux : taureaux, chevaux, cerfs, bisons peints sur les parois de la grotte de Lascaux. L'homme préhistorique a d'abord peint les animaux avant de se peindre lui-même. L'animal est au fondement même de l'art humain. La relation homme-animal est originelle.",
        examTip: "Utilise Lascaux comme argument ultime d'ouverture ou d'introduction : l'art commence avec l'animal. La relation homme-animal est vieille de 17 000 ans. Impossible de faire plus ancien.",
        keyQuote: ''
    },

    // ==================== PODCASTS (5 oeuvres) ====================

    {
        id: 'fc-vivre-ensemble',
        title: '"Les animaux et nous, comment vivre ensemble ?"',
        author: 'France Culture',
        year: '',
        category: 'podcast',
        categoryLabel: 'Podcast',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🎧',
        coverGradient: 'linear-gradient(135deg, #00cec9, #81ecec)',
        summary: "Podcast qui explore la question de la cohabitation entre humains et animaux dans le monde contemporain. Interviews de scientifiques, philosophes et acteurs de terrain sur les enjeux concrets du « vivre ensemble » inter-espèces : animaux en ville, élevage, faune sauvage.",
        examTip: "Utilise ce podcast pour des arguments contemporains et concrets sur la cohabitation homme-animal. Bon pour montrer que le sujet est d'actualité brûlante.",
        keyQuote: ''
    },
    {
        id: 'fc-etat-sauvage',
        title: '"Faut-il renvoyer le monde animal à l\'état sauvage ?"',
        author: 'France Culture',
        year: '',
        category: 'podcast',
        categoryLabel: 'Podcast',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '🎙️',
        coverGradient: 'linear-gradient(135deg, #02c4bf, #77e8e3)',
        summary: "Débat philosophique et scientifique : doit-on arrêter toute domestication et laisser les animaux vivre librement ? Faut-il abolir les zoos, l'élevage, les animaux de compagnie ? Le podcast explore les limites du retour au sauvage et questionne notre dépendance mutuelle avec les animaux.",
        examTip: "Utilise ce podcast pour nuancer le débat : le retour total au sauvage est-il possible ou souhaitable ? Argument pour la complexité du sujet.",
        keyQuote: ''
    },
    {
        id: 'fc-avenir-homme',
        title: '"L\'animal est l\'avenir de l\'homme"',
        author: 'France Culture',
        year: '',
        category: 'podcast',
        categoryLabel: 'Podcast',
        difficulty: 'moyen',
        diffLabel: 'Moyen',
        icon: '🔮',
        coverGradient: 'linear-gradient(135deg, #04bab6, #6de2de)',
        summary: "Podcast qui explore l'idée que l'avenir de l'humanité passe par une meilleure compréhension et un meilleur traitement des animaux. Biomimétisme, intelligence animale, éthique : les animaux ont beaucoup à nous apprendre pour construire un monde durable.",
        examTip: "Utilise ce podcast pour argumenter que protéger les animaux, c'est préparer l'avenir de l'humanité. L'animal comme modèle et source d'inspiration (biomimétisme).",
        keyQuote: ''
    },
    {
        id: 'fc-museum-new-york',
        title: '"Le Musée d\'histoire naturelle de New York"',
        author: 'France Culture',
        year: '',
        category: 'podcast',
        categoryLabel: 'Podcast',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '🏛️',
        coverGradient: 'linear-gradient(135deg, #06b0ad, #63dcd8)',
        summary: "Podcast sur le célèbre muséum américain et sa manière de représenter les animaux : dioramas naturalistes, squelettes de dinosaures, collections d'insectes. Le musée pose la question de la muséification du vivant : mettre un animal empaillé sous vitrine, est-ce le respecter ou le réduire à un objet ?",
        examTip: "Utilise ce podcast pour questionner la mise en spectacle des animaux dans les musées. L'animal-objet de collection vs l'animal-être vivant.",
        keyQuote: ''
    },
    {
        id: 'fc-animaux-ecran',
        title: '"Les animaux à l\'écran"',
        author: 'France Culture',
        year: '',
        category: 'podcast',
        categoryLabel: 'Podcast',
        difficulty: 'facile',
        diffLabel: 'Facile',
        icon: '📺',
        coverGradient: 'linear-gradient(135deg, #08a6a3, #59d6d2)',
        summary: "Podcast qui analyse la représentation des animaux au cinéma et à la télévision : documentaires animaliers, films d'animation, utilisation d'animaux réels sur les tournages. Comment l'écran façonne notre regard sur les animaux ? Entre émerveillement et exploitation, le podcast décrypte les images animales.",
        examTip: "Utilise ce podcast pour parler de l'image de l'animal dans les médias et la culture populaire. L'écran comme filtre entre nous et les animaux réels.",
        keyQuote: ''
    }
];
